# Generated by Django 5.0.14 on 2026-06-21 02:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Court A', max_length=100)),
                ('surface_type', models.CharField(choices=[('ARTIFICIAL', 'Artificial turf'), ('NATURAL', 'Natural grass'), ('INDOOR', 'Indoor')], default='ARTIFICIAL', max_length=12)),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClosureException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='futsals.court')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Futsal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timezone', models.CharField(default='Asia/Kathmandu', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='PENDING', max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_futsals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='court',
            name='futsal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='futsals.futsal'),
        ),
        migrations.CreateModel(
            name='FutsalRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager')], max_length=10)),
                ('futsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='futsals.futsal')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_roles', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='futsal_roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='futsals.court')),
            ],
            options={
                'ordering': ['weekday', 'open_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='closureexception',
            constraint=models.UniqueConstraint(fields=('court', 'date'), name='uniq_court_closure_date'),
        ),
        migrations.AddIndex(
            model_name='futsal',
            index=models.Index(fields=['status'], name='futsals_fut_status_b0bd56_idx'),
        ),
        migrations.AddIndex(
            model_name='futsal',
            index=models.Index(fields=['city'], name='futsals_fut_city_666098_idx'),
        ),
        migrations.AddConstraint(
            model_name='court',
            constraint=models.UniqueConstraint(fields=('futsal', 'name'), name='uniq_court_name_per_futsal'),
        ),
        migrations.AddIndex(
            model_name='futsalrole',
            index=models.Index(fields=['futsal', 'role'], name='futsals_fut_futsal__635464_idx'),
        ),
        migrations.AddConstraint(
            model_name='futsalrole',
            constraint=models.UniqueConstraint(fields=('user', 'futsal', 'role'), name='uniq_user_futsal_role'),
        ),
        migrations.AddConstraint(
            model_name='operatinghours',
            constraint=models.UniqueConstraint(fields=('court', 'weekday'), name='uniq_court_weekday_hours'),
        ),
        migrations.AddConstraint(
            model_name='operatinghours',
            constraint=models.CheckConstraint(check=models.Q(('open_time__lt', models.F('close_time'))), name='hours_open_before_close'),
        ),
    ]
