# Generated by Django 5.0.14 on 2026-06-21 02:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('futsals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('days_mask', models.PositiveSmallIntegerField(default=127)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('priority', models.IntegerField(default=0)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='futsals.court')),
            ],
            options={
                'ordering': ['-priority', 'start_time'],
                'indexes': [models.Index(fields=['court', 'is_active'], name='pricing_pri_court_i_952b96_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='pricerule',
            constraint=models.CheckConstraint(check=models.Q(('start_time__lt', models.F('end_time'))), name='pricerule_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='pricerule',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='pricerule_price_nonneg'),
        ),
    ]
