# Generated by Django 5.0.14 on 2026-06-21 06:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_overlap_exclusion_constraint'),
        ('futsals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('proposed_start', models.DateTimeField()),
                ('proposed_end', models.DateTimeField(blank=True, null=True)),
                ('format', models.CharField(choices=[('5s', '5-a-side'), ('7s', '7-a-side'), ('OTHER', 'Other')], default='5s', max_length=6)),
                ('skill_level', models.CharField(blank=True, max_length=50)),
                ('max_players', models.PositiveSmallIntegerField(default=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FULL', 'Full'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match', to='bookings.booking')),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='futsals.court')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['proposed_start'],
            },
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('JOINED', 'Joined'), ('LEFT', 'Left'), ('REMOVED', 'Removed')], default='JOINED', max_length=10)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='matchmaking.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status', 'proposed_start'], name='matchmaking_status_1f0180_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['city'], name='matchmaking_city_39354e_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchplayer',
            constraint=models.UniqueConstraint(fields=('match', 'user'), name='uniq_match_player'),
        ),
    ]
